package constant

const (
	MONGODB_ADDRESS = "DB_ADDRESS"
	MONGODB_ROOT_USER = "DB_ROOT_USERNAME"
	MONGODB_ROOT_PSW = "DB_ROOT_PASSWORD"
	REDIS_ADDRESS = "REDIS_ADDRESS"
	ZOOKEEPER_ADDRESS = "ZK_ADDRESS"
)
